project:
  type: website

website:
  title: "Careers@DACSS"

  # page footer
  page-footer: 
    left: "Copyright @ DACSS" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 
        
        
  site-url: https://dacss.github.io/Resume/
  
  twitter-card:
    creator: "@UMassDACSS"
    site: "@UMassDACSS"
  
  favicon: images/DACSS_Round_Network.png
  
  open-graph: true
  navbar:
    background: "#881c1c"
    text: UMass Amherst
    pinned: true
    search: true
    right:
      - text: "Home"
        href: index.qmd
        
      - text: "People"
        href: people.qmd
        
      - text: "Projects"
        href: projects.qmd
      
      - text: "Contact"
        href: contact.qmd
        
      - text: "For Employers"
        href: for_employers.qmd
      
      - text: "Menu"
        menu: 
          - text: "student"
            href: people.qmd
          - text: "faculty"
            href: faculty.qmd
          - text: "contact"
            href: contact.qmd
format:
  html:
    smooth-scroll: true # enabled smooth scrolling
    mainfont: "Atkinson Hyperlegible" # defined a style in .scss and used the name here
    linkcolor: "#881c1c"
    toc: true
    theme: litera
    code-copy: true
    code-overflow: wrap

    

editor: visual



