project:
  type: website
  
format:
  html:
    # css:
    #   - styles.css
    smooth-scroll: true # enabled smooth scrolling
    mainfont: "Atkinson Hyperlegible" # defined a style in .scss and used the name here
    linkcolor: "#881c1c"
    toc: true
    theme: litera
    code-copy: true
    code-overflow: wrap
    
    
website:
  title: "Careers@DACSS"

  # page footer
  page-footer: 
    left: "Copyright @ DACSS" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 
        
  site-url: https://dacss.github.io/Resume/
  
  twitter-card:
    creator: "@UMassDACSS"
    site: "@UMassDACSS"
  
  favicon: images/DACSS_Round_Network.png
  
  open-graph: true
  navbar:
    background: "#881c1c"
    text: UMass Amherst
    pinned: true
    search: true
    right:
      - text: "Home"
        href: index.qmd

editor: visual



