project:
  type: website

website:
  title: "Data Analytics and Computational Social Science"
  site-url: https://dacss.github.io/Resume/
  twitter-card:
    creator: "@UMassDACSS"
    site: "@UMassDACSS"
  favicon: images/DACSS_Round_Network.png
  navbar:
    background: "#881c1c"
    logo: images/UMass White Wordmark Horiz.png
    right:
      - text: "People"
        href: index.qmd
      - href: https://umass.edu/sbs/dacss
        text: "DACSS"
      - icon: github
        href: https://github.com/DACSS
        aria-label: GitHub

format:
  html:
    mainfont: Open Sans
    linkcolor: "#881c1c"
    toc: true
    theme: 
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]



