project:
  type: website
  
format:
  html:
    css:
      - styles.css
    smooth-scroll: true # enabled smooth scrolling
    mainfont: "Atkinson Hyperlegible" # defined a style in .scss and used the name here
    linkcolor: "#881c1c"
    toc: true
    theme: litera
    code-copy: true
    code-overflow: wrap
    include-in-header: assets/bootstrap_dependencies.html
    
website:
  title: "Careers@DACSS"
  google-analytics: "G-KT7T9GWL9H"
  
  cookie-consent: true

  # page footer
  page-footer: 
    left: "Copyright @ DACSS" 
    right: 
      - icon: github`
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/umassdacss
        
  site-url: https://dacss.github.io/Resume/
  
  twitter-card:
    creator: "@UMassDACSS"
    site: "@UMassDACSS"
  
  favicon: images/DACSS_Round_Network.png
  
  open-graph: true
  navbar:
    background: "#881c1c"
    text: UMass Amherst
    pinned: true
    search: true
    right:
      - text: "For Employers"
        href: pages/for_employers.qmd
        
      - text: "Home"
        href: index.qmd
        
      - text: "People"
        href: people.qmd

      - text: "Projects"
        href: pages/projects.qmd
      
      - text: "Contact"
        href: pages/contact.qmd

editor: visual



